source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '12.0'

target 'RxMapKit_Example' do
  pod 'RxMapKit', :path => '../'
  pod 'SnapKit'
  
  # UI Test Tools
  pod 'LookinServer', :configurations => ['Debug']

  target 'RxMapKit_Tests' do
    inherit! :search_paths

#    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
