use_frameworks!

platform :ios, '12.0'

target 'RxMapKit_Example' do
  pod 'RxMapKit', :path => '../'

  target 'RxMapKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
